### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by cg-cnu** [lispyclouds/mpw-rs#2]
<div align=center>
<img width="256" alt="masterkey 4" src="https://user-images.githubusercontent.com/2767425/31902097-4979d340-b841-11e7-8655-2d24515dbccf.png">
</div>

🙂

**Comment by ranjithrajv** [comment]
Thanks for your contribution @cg-cnu. The logo is added to the documentation. https://github.com/rustindia/mpw-rs/commit/a209356347506a129209a24ae6dcf8eefba89043

**Comment by cg-cnu** [comment]
Thanks @ranjithrajv
